//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_Final_M47_G8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public int IdPais { get; set; }
        public string NombrePais { get; set; }
    }
}
